A matrix A of type 2 × 2 has eigenvalues equal to λ1 = 1, λ2 = 2. Determine the eigenvalues of the matrix

[ (4, 3; 3, -4) * A * (4, 3; 3, -4) ]

In [1]:
import numpy as np

In [2]:
lambda1 = 1
lambda2 = 2

In [3]:
A = np.array([[lambda1, 0],
              [0, lambda2]])
print("Matrix A:", A)

Matrix A: [[1 0]
 [0 2]]


In [4]:
U = np.array([
        [4, 3],
        [3, -4]
    ], dtype=np.dtype(float))

print("Matrix U:", U)

Matrix U: [[ 4.  3.]
 [ 3. -4.]]


In [5]:
Ut = U.transpose()

print("Matrix Ut:", Ut)


Matrix Ut: [[ 4.  3.]
 [ 3. -4.]]


In [6]:
d = np.linalg.det(U)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -25.00


Non-singular, independent matrix


**Check if orthogonal:**

In [7]:
mult = np.dot(U, Ut)
mult

array([[25.,  0.],
       [ 0., 25.]])

In [8]:
identity_matrix = np.identity(len(U))
identity_matrix

array([[1., 0.],
       [0., 1.]])

In [9]:
print(np.allclose(mult, identity_matrix))

False


In [10]:
# 2 zpusob (check if matrix is orthogonal)
# print(np.allclose(Ut, np.linalg.inv(U)))

The matrix U is **non-orthogonal**

In [11]:
result_matrix = np.dot(np.dot(U.T, A), U)

In [12]:
eigenvalues_result = np.linalg.eigvals(result_matrix)

In [14]:
print("Matrix (Ut * A * U):")
print(result_matrix)
print("\nEigenvalues of the matrix (Ut * A * U):")
print(eigenvalues_result)
print("\nEigenvalues of the matrix A:")
print(np.diag(A))  # Используем np.diag, чтобы получить собственные значения матрицы A


Matrix (Ut * A * U):
[[ 34. -12.]
 [-12.  41.]]

Eigenvalues of the matrix (Ut * A * U):
[25. 50.]

Eigenvalues of the matrix A:
[1 2]
