Determine the signature of the quadratic form of the function **f**

f(x,y,z) = 2*(x - y)^2 + (y - z)^2 - 2*x*z

In [3]:
import numpy as np
from sympy import symbols, Symbol, ones, eye, simplify

In [4]:
x,y,z = symbols('x y z')

In [5]:
f = 2*(x - y)**2 + (y - z)**2 - 2*x*z
f

-2*x*z + 2*(x - y)**2 + (y - z)**2

In [6]:
fun = 2*x**2 + 3*y**2 + z**2 - 4*x*y - 2*y*z - 2*x*z
fun

2*x**2 - 4*x*y - 2*x*z + 3*y**2 - 2*y*z + z**2

In [7]:
a = 2
e = 3
k = 1
b_d = -4
f_h = -2
c_g = -2

In [8]:
A = np.array([
        [a, b_d/2, c_g/2],
        [b_d/2, e, f_h/2],
        [c_g/2, f_h/2, k]
    ], dtype=np.dtype(float))


print("Matrix A:")
print(A)

Matrix A:
[[ 2. -2. -1.]
 [-2.  3. -1.]
 [-1. -1.  1.]]


In [9]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues", eigenvalues)

Eigenvalues [-0.71447874  4.57120142  2.14327732]


### **The end result:** ### 

number of positive eigenvalues, number of negative eigenvalues, number of zero eigenvalues

In [12]:
num_positive = np.sum(eigenvalues > 0)
num_negative = np.sum(eigenvalues < 0)
num_zero = np.sum(eigenvalues == 0)

print(num_positive, num_negative, num_zero)

2 1 0
